---
- name: Create .kube directory
  file: path=/home/ubuntu/.kube state=directory

- name: Copy .kube/config
  copy:
    src: /tmp/kube_config
    dest: /home/ubuntu/.kube/config
  
- name: Join Cluster
  command: kubeadm join --discovery-file /home/ubuntu/.kube/config
  become: yes
