---
- name: Open kube API port
  command: iptables -I INPUT -p tcp -m tcp --dport 6443 -j ACCEPT
  become: yes

- name: Save iptables configuration
  command: iptables-save
  become: yes

- name: Generate kubernetes token
  command: kubeadm token generate
  become: yes
  register: token

- name: Initialize Kubernetes
  # Ignore single core CPU check. OCI free tier does have its drawbacks
  command: kubeadm init --token="{{ token.stdout_lines[0] }}" --kubernetes-version=v1.22.2 --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU
  become: yes

- name: Create ~/.kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: '0755'

- name: Copy admin kubeconfig to ~/.kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    remote_src: yes
  become: yes

- name: Retrieve ~/.kube/config file
  fetch:
    src: /home/ubuntu/.kube/config
    dest: /tmp/kube_config
    flat: yes

- name: Install flannel overlay network
  shell: curl -sSL https://raw.githubusercontent.com/coreos/flannel/v0.14.0/Documentation/kube-flannel.yml | kubectl apply -f -
